### PR TITLE
Clean up .gitattributes

### PR DESCRIPTION
**Pull request by vgturtle127**
Just remove the commented out stuff, we can always add it later.

There are better ways to handle Visual Studio files, like just treating them as text files or automatically using the CLRF encoding so that Windows doesn't complain.

It doesn't matter as much right now since you have kept the structure so tidy. :wink:

### CODE REVIEW

**Comment by beannaich** [comment]
Rebase this one and I'll merge it in.

**Comment by vgturtle127** [comment]
@beannaich I always have trouble with rebases, so this might take a while. :disappointed:

**Comment by beannaich** [comment]
@vgturtle127 if you wait till tomorrow I can walk you through it :smile:

**Comment by vgturtle127** [comment]
@beannaich Maybe that would be best. I have done it successfully with some projects, but with some (like PCSX2 and Dolphin) I can't seem to get the hang of it...

**Comment by beannaich** [comment]
Okay, since you forked you should have my fork set up as the `upstream` remote automatically. To verify this do:

```
$ git remote -v
origin  https://github.com/vgturtle127/psxact.git (fetch)
origin  https://github.com/vgturtle127/psxact.git (push)
upstream        https://github.com/beannaich/psxact.git (fetch)
upstream        https://github.com/beannaich/psxact.git (push)
```

If you don't have it, just run:

```
$ git remote add upstream https://github.com/beannaich/psxact.git
```

Once you have verified that you have the `upstream` remote configured, do a fetch:

```
$ git fetch upstream
```

That will download all of the commit data from my repo into your local copy. Next you'll switch to your branch (`patch-2` in this case):

```
$ git checkout patch-2
```

Then you'll want to rebase (you can also do an [interactive rebase](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history) to clean up the pull request if you want):

```
$ git rebase upstream/develop
```

This should work just fine without any conflicts. If there are conflicts, just go to the file in error and fix it normally, then run `$ git rebase --continue` to let the rebase process run. Once it's complete, you'll have your local copy fixed (and you can verify that in your favorite git UI), and you'll need to force push:

```
$ git push -f patch-2
```

Once that's done, this pull request will be updated and I can merge it in :smile: If you run into any issues and you want to back out (once you force push this is no longer an option) just run:

```
$ git reset --hard
```

**Comment by vgturtle127** [comment]
@beannaich Everything works fine except the git rebase upstream/develop. It says "Needed a single revision, invalid upstream upstream/develop".

This is the part I can't wrap my head around. :laughing:

**Comment by beannaich** [comment]
@vgturtle127 That's odd, I cloned your fork and ran the commands myself and it seemed to work :smile: However, you should be able to use your fork's develop branch for the rebase after you re-synchronize with `upstream`. Try the following:

```
$ git fetch upstream
$ git checkout develop
$ git merge upstream/develop # should be a fast forward merge
$ git push develop
$ git checkout patch-2
$ git rebase develop
$ git push -f patch-2
```

**Comment by vgturtle127** [comment]
@beannaich I get fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository. when I try git fetch upstream.

Also, I get merge: upstream/develop - not something we can merge when I try to merge now.

I don't have any uncommited changes, so that isn't it.

I also get fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists. when I try to fetch upstream on the patch-2 branch...

I wish rebasing had a GUI counterpart in GitHub desktop. :wink:

**Comment by beannaich** [comment]
@vgturtle127 what does your `$ git remote -v` look like?

**Comment by vgturtle127** [comment]
@beannaich Like this:

beannaich       https://github.com/beannaich/psxact.git (fetch)
beannaich       https://github.com/beannaich/psxact.git (push)
origin  https://github.com/vgturtle127/psxact.git (fetch)
origin  https://github.com/vgturtle127/psxact.git (push)

**Comment by beannaich** [comment]
Replace `upstream` with `beannaich` in the original instructions :smile:

**Comment by vgturtle127** [comment]
@beannaich Well, I'm stupid. :laughing: 

OK, so now it tells me "git merge beannaich/develop
Already up-to-date.
C:\Users\Turtle\Documents\GitHub\psxact [develop]> git push develop
fatal: You are pushing to remote 'develop', which is not the upstream of
your current branch 'develop', without telling me what to push
to update which remote branch."

Oh, my head. :confounded:

**Comment by beannaich** [comment]
@vgturtle127 try the original instructions way up in this thread haha.
Where you rebase on beannaich/develop

**Comment by vgturtle127** [comment]
@beannaich OK, now I am mostly there. :laughing: 

Now I get "fatal: You are pushing to remote 'patch-2', which is not the upstream of
your current branch 'patch-2', without telling me what to push
to update which remote branch."

**Comment by beannaich** [comment]
`git push -f origin/patch2` :smile:

**Comment by vgturtle127** [comment]
@beannaich Ah! Uh, wait...

I am still getting "fatal: You are pushing to remote 'origin/patch-2', which is not the upstream of
your current branch 'patch-2', without telling me what to push
to update which remote branch."

I tried with your repo name, and it still gave me the same message. Oh, please just work. :sos:

**Comment by beannaich** [comment]
This should work *fingers crossed*

```
$ git rebase origin/develop
$ git push -f origin/patch-2
```

**Comment by vgturtle127** [comment]
@beannaich This worked: git rebase origin/develop

However, git push -f origin/patch-2
fatal: You are pushing to remote 'origin/patch-2', which is not the upstream of
your current branch 'patch-2', without telling me what to push
to update which remote branch.

didn't work. :cry:

**Comment by beannaich** [comment]
@vgrurtle127 check your e-mail. We'll continue this troubleshooting via IM or IRC

**Pull request merged**
